//! The MCP server implementation: the tool surface and result rendering.
//!
//! Unlike a server with a fixed tool set, this one is a **proxy**: the
//! browser tools come from the upstream Playwright MCP server's own
//! `tools/list` (cached per warm instance, see [`crate::playwright`]), so
//! `ServerHandler::list_tools` / `call_tool` are written by hand instead of
//! generated by `#[tool_router]`. Two tools are local:
//!
//! - `playwright_status` — reachability, upstream identity, session/cache
//!   state, and the exact remediation when something is off;
//! - `playwright_reset_session` — closes the cached upstream browser session.
//!
//! Every other name is forwarded verbatim after the proxy's policy: gated
//! tools refused unless enabled, `filename` stripped, numeric clamps, jpeg
//! screenshots by default, ANSI removed and text bounded on the way back,
//! and the file-only snapshot link replaced by an inline accessibility
//! snapshot so the agent sees the page without host filesystem access.
//!
//! Alongside the tools, this server publishes **skills** — natural-language
//! playbooks served over the MCP resources primitive under `skill://` URIs.
//! See [`crate::skills`]; the handlers at the bottom of this file are the
//! protocol surface for them.

use rmcp::model::{
    CallToolRequestParams, CallToolResponse, CallToolResult, ContentBlock, Implementation,
    JsonObject, ListResourceTemplatesResult, ListResourcesResult, ListToolsResult,
    PaginatedRequestParams, ReadResourceRequestParams, ReadResourceResponse, ReadResourceResult,
    ResourceContents, ServerCapabilities, ServerInfo, Tool, ToolAnnotations,
};
use rmcp::service::{RequestContext, RoleServer};
use rmcp::{ErrorData, ServerHandler};
use schemars::JsonSchema;
use serde::Deserialize;
use serde_json::{json, Value};

use crate::playwright::{self, Client, Config, Error};
use crate::skills;

/// The MCP server for this component. One instance is created per request —
/// the transport is stateless (2026-07-28 spec), so nothing lives on this
/// struct; the upstream session cache is a static in [`crate::playwright`].
#[derive(Clone, Default)]
pub struct PlaywrightServer;

/// Local diagnostic tool.
pub const STATUS_TOOL: &str = "playwright_status";
/// Local session-reset tool.
pub const RESET_TOOL: &str = "playwright_reset_session";
/// The upstream tool the proxy calls to inline snapshots.
const SNAPSHOT_TOOL: &str = "browser_snapshot";

/// `playwright_status` takes no arguments.
#[derive(Debug, Default, Deserialize, JsonSchema)]
pub struct StatusParams {}

/// `playwright_reset_session` takes no arguments.
#[derive(Debug, Default, Deserialize, JsonSchema)]
pub struct ResetParams {}

fn schema_of<T: JsonSchema>() -> JsonObject {
    match serde_json::to_value(schemars::schema_for!(T)) {
        Ok(Value::Object(map)) => map,
        _ => {
            let mut map = JsonObject::new();
            map.insert("type".to_owned(), Value::String("object".to_owned()));
            map
        }
    }
}

/// The two tools this proxy implements itself.
fn local_tools() -> Vec<Tool> {
    let mut status = Tool::new(
        STATUS_TOOL,
        "Check the upstream Playwright MCP server: reachable?, its name/version and \
         negotiated protocol, whether a browser session and the tool list are cached on this \
         instance, the configured base URL and gates, and — when something is off — the exact \
         setup fix (loopback grants, --allowed-hosts, --host 127.0.0.1, bearer token). Call it \
         first, and whenever a browser tool fails with a connection or 403 error.",
        schema_of::<StatusParams>(),
    );
    status.annotations = Some(ToolAnnotations::from_raw(
        Some("Playwright upstream status".to_owned()),
        Some(true),
        Some(false),
        Some(true),
        Some(false),
    ));
    let mut reset = Tool::new(
        RESET_TOOL,
        "Close the cached upstream browser session (DELETE) so the next browser tool call \
         starts a fresh context: no tabs, cookies or page state survive. Use it to recover \
         from a wedged page, a dialog you cannot dismiss, or a stale tool list; the next call \
         re-initializes automatically.",
        schema_of::<ResetParams>(),
    );
    reset.annotations = Some(ToolAnnotations::from_raw(
        Some("Reset Playwright session".to_owned()),
        Some(false),
        Some(true),
        Some(true),
        Some(false),
    ));
    vec![status, reset]
}

/// A structured result with a hand-written readable text block instead of
/// the JSON dump `CallToolResult::structured` would produce.
fn shaped(value: Value, text: impl Into<String>) -> CallToolResult {
    let mut result = CallToolResult::structured(value);
    result.content = vec![ContentBlock::text(text.into())];
    result
}

fn failed(err: &Error, cfg: &Config) -> CallToolResult {
    CallToolResult::error(vec![ContentBlock::text(err.message(cfg))])
}

impl PlaywrightServer {
    pub fn new() -> Self {
        Self
    }

    /// Names of the tools this server exposes right now: the local ones plus
    /// whatever upstream tools are cached on this instance (no I/O — the
    /// discovery document is answered outside the request lock).
    pub fn tool_names() -> Vec<String> {
        let mut names: Vec<String> = local_tools()
            .into_iter()
            .map(|t| t.name.into_owned())
            .collect();
        names.extend(playwright::cached_tool_names(&playwright::config()));
        names
    }

    /// Reachability and setup diagnostics for the upstream.
    #[tracing::instrument(name = "tool.playwright_status", skip(self))]
    async fn playwright_status(&self) -> CallToolResult {
        let cfg = playwright::config();
        let client = Client::new(cfg.clone());
        let outcome = client.ping().await;
        let mut hints: Vec<String> = Vec::new();
        // Warm (and report) the upstream tool list too: it validates the
        // whole tools/list path, tells the caller how many tools the
        // upstream offers at its current --caps, and makes GET / complete.
        if outcome.is_ok() {
            if let Err(err) = client.tools().await {
                hints.push(format!(
                    "ping succeeded but tools/list failed: {}",
                    err.message(&cfg)
                ));
            }
        }
        let snap = playwright::snapshot(&cfg);
        if !cfg.base_url.ends_with("/mcp") {
            hints.push(format!(
                "{} does not end in /mcp; @playwright/mcp serves streamable HTTP at /mcp",
                playwright::BASE_URL_ENV
            ));
        }
        if cfg.via_loopback() {
            hints.push(format!(
                "upstream is reached through the Desktop loopback sentinel: start it with \
                 `{}` and keep the three loopback grants in place",
                cfg.launch_command()
            ));
        }
        if cfg.allow_unsafe {
            hints.push(
                "PLAYWRIGHT_ALLOW_UNSAFE=true: browser_evaluate / browser_run_code_unsafe / \
                 browser_file_upload / browser_drop are exposed"
                    .to_owned(),
            );
        }
        if !cfg.auto_snapshot {
            hints.push(
                "PLAYWRIGHT_AUTO_SNAPSHOT=false: call browser_snapshot yourself after every \
                 action (action results only carry a file link)"
                    .to_owned(),
            );
        }
        let (status, reachable, remediation, upstream) = match &outcome {
            Ok(session) => (
                "ok",
                true,
                None,
                json!({
                    "name": session.server_name,
                    "version": session.server_version,
                    "protocolVersion": session.protocol_version,
                }),
            ),
            Err(err) => {
                let status = match err {
                    Error::Transport { .. } => "unreachable",
                    Error::HostRejected { .. } => "host_rejected",
                    Error::Auth { .. } if cfg.token.is_none() => "missing",
                    Error::Auth { .. } => "invalid",
                    _ => "error",
                };
                (status, false, Some(err.message(&cfg)), Value::Null)
            }
        };
        let value = json!({
            "status": status,
            "reachable": reachable,
            "base_url": cfg.base_url,
            "via_loopback": cfg.via_loopback(),
            "upstream": upstream,
            "session": {
                "cached": snap.session.is_some(),
                "initializes_on_this_instance": snap.initialize_count,
            },
            "tools": {
                "cached": snap.tools_cached,
                "cache_age_secs": snap.tools_age_secs,
                "ttl_secs": cfg.tools_ttl_secs,
            },
            "allow_unsafe": cfg.allow_unsafe,
            "auto_snapshot": cfg.auto_snapshot,
            "token_configured": cfg.token.is_some(),
            "credential": {
                "ref": playwright::SECRET_REF,
                "env": playwright::TOKEN_ENV,
                "required": false,
            },
            "remediation": remediation,
            "hints": hints,
            "launch_command": cfg.launch_command(),
        });
        let mut text = match &outcome {
            Ok(session) => format!(
                "Playwright MCP upstream OK at {}: {} {} (MCP {}). Session cached: {}; tools \
                 cached: {}.",
                cfg.base_url,
                session.server_name,
                session.server_version,
                session.protocol_version,
                snap.session.is_some(),
                snap.tools_cached
                    .map(|n| n.to_string())
                    .unwrap_or_else(|| "no".to_owned())
            ),
            Err(err) => format!("Playwright MCP upstream {status}: {}", err.message(&cfg)),
        };
        for hint in &hints {
            text.push_str("\n- ");
            text.push_str(hint);
        }
        let mut result = shaped(value, text);
        if outcome.is_err() {
            result.is_error = Some(true);
        }
        result
    }

    /// Closes the cached upstream session.
    #[tracing::instrument(name = "tool.playwright_reset_session", skip(self))]
    async fn playwright_reset_session(&self) -> CallToolResult {
        let cfg = playwright::config();
        let client = Client::new(cfg.clone());
        match client.reset_session().await {
            Ok(None) => shaped(
                json!({"status": "nothing_to_reset", "had_session": false}),
                "No upstream session was cached on this instance; the next browser tool call \
                 initializes a fresh one.",
            ),
            Ok(Some(status)) => shaped(
                json!({"status": "reset", "had_session": true, "upstream_status": status}),
                format!(
                    "Closed the upstream browser session (DELETE answered HTTP {status}). The \
                     next browser tool call starts a fresh context: navigate again."
                ),
            ),
            Err(err) => {
                // The cache is already cleared; the next call re-initializes.
                let mut result = shaped(
                    json!({"status": "reset_local_only", "had_session": true, "error": err.message(&cfg)}),
                    format!(
                        "Forgot the cached session, but the upstream DELETE failed: {}. The \
                         next browser tool call will initialize a new session anyway.",
                        err.message(&cfg)
                    ),
                );
                result.is_error = Some(true);
                result
            }
        }
    }

    /// Forwards a browser tool call to the upstream.
    #[tracing::instrument(name = "tool.browser", skip(self, arguments), fields(tool = %name))]
    async fn forward(
        &self,
        name: &str,
        mut arguments: JsonObject,
    ) -> Result<CallToolResult, ErrorData> {
        let cfg = playwright::config();
        if playwright::is_unsafe_tool(name) && !cfg.allow_unsafe {
            return Ok(CallToolResult::error(vec![ContentBlock::text(
                playwright::gated_message(name),
            )]));
        }
        let client = Client::new(cfg.clone());

        // Route check against the upstream's own list (refreshed once on a
        // miss so a newly enabled --caps tool is not refused by a stale cache).
        let known = |tools: &[Value]| {
            tools
                .iter()
                .any(|t| t.get("name").and_then(Value::as_str) == Some(name))
        };
        let tools = match client.tools().await {
            Ok(tools) => tools,
            Err(err) => return Ok(failed(&err, &cfg)),
        };
        if !known(&tools) {
            let refreshed = client.refresh_tools().await.unwrap_or(tools);
            if !known(&refreshed) {
                let mut offered: Vec<&str> = refreshed
                    .iter()
                    .filter_map(|t| t.get("name").and_then(Value::as_str))
                    .filter(|n| cfg.allow_unsafe || !playwright::is_unsafe_tool(n))
                    .collect();
                offered.sort_unstable();
                return Err(ErrorData::invalid_params(
                    format!(
                        "unknown tool {name:?}; this server offers {STATUS_TOOL}, {RESET_TOOL} \
                         and the upstream Playwright tools: {}",
                        offered.join(", ")
                    ),
                    None,
                ));
            }
        }

        let mut notes = playwright::sanitize_arguments(name, &mut arguments);
        let upstream = match client.call_tool(name, Value::Object(arguments)).await {
            Ok(result) => result,
            Err(err) => return Ok(failed(&err, &cfg)),
        };
        let (mut result, is_error) = render_result(&upstream);

        // Inline the accessibility snapshot the upstream only linked to.
        if cfg.auto_snapshot && !is_error && name != SNAPSHOT_TOOL {
            let linked = result.content.iter().position(|block| match block {
                ContentBlock::Text(text) => playwright::has_snapshot_link(&text.text),
                _ => false,
            });
            if let Some(index) = linked {
                match client.call_tool(SNAPSHOT_TOOL, json!({})).await {
                    Ok(snapshot) => {
                        let snapshot_text = first_text(&snapshot);
                        let snapshot_failed =
                            snapshot.get("isError").and_then(Value::as_bool) == Some(true);
                        if snapshot_failed {
                            notes.push(format!(
                                "browser_snapshot after the action failed: {}",
                                playwright::strip_ansi(snapshot_text.trim())
                            ));
                        } else if let ContentBlock::Text(text) = &mut result.content[index] {
                            if let Some(merged) =
                                playwright::inline_snapshot(&text.text, &snapshot_text)
                            {
                                text.text = playwright::bounded_text(merged);
                            }
                        }
                    }
                    Err(err) => notes.push(format!(
                        "could not inline the snapshot after the action: {}",
                        err.message(&cfg)
                    )),
                }
            }
        }

        if !notes.is_empty() {
            let mut text = String::from("### Proxy notes\n");
            for note in &notes {
                text.push_str("- ");
                text.push_str(note);
                text.push('\n');
            }
            result
                .content
                .push(ContentBlock::text(text.trim_end().to_owned()));
        }
        Ok(result)
    }
}

/// The first text block of an upstream result, ANSI-stripped.
fn first_text(result: &Value) -> String {
    result
        .get("content")
        .and_then(Value::as_array)
        .and_then(|blocks| {
            blocks.iter().find_map(|b| {
                (b.get("type").and_then(Value::as_str) == Some("text"))
                    .then(|| b.get("text").and_then(Value::as_str))
                    .flatten()
            })
        })
        .map(playwright::strip_ansi)
        .unwrap_or_default()
}

/// Converts an upstream `tools/call` result into ours: content blocks bounded
/// and ANSI-stripped, `isError` honoured, `structuredContent` carried over.
fn render_result(upstream: &Value) -> (CallToolResult, bool) {
    let is_error = upstream.get("isError").and_then(Value::as_bool) == Some(true);
    let mut content: Vec<ContentBlock> = Vec::new();
    for block in upstream
        .get("content")
        .and_then(Value::as_array)
        .map(|v| v.as_slice())
        .unwrap_or_default()
        .iter()
        .take(playwright::MAX_CONTENT_BLOCKS)
    {
        let rendered = match block.get("type").and_then(Value::as_str) {
            Some("text") => ContentBlock::text(playwright::bounded_text(playwright::strip_ansi(
                block.get("text").and_then(Value::as_str).unwrap_or(""),
            ))),
            Some("image") => {
                let data = block.get("data").and_then(Value::as_str).unwrap_or("");
                let mime = block
                    .get("mimeType")
                    .and_then(Value::as_str)
                    .unwrap_or("image/png");
                ContentBlock::image(data, mime)
            }
            _ => match serde_json::from_value::<ContentBlock>(block.clone()) {
                Ok(parsed) => parsed,
                Err(_) => ContentBlock::text(playwright::bounded_text(block.to_string())),
            },
        };
        content.push(rendered);
    }
    if content.is_empty() {
        content.push(ContentBlock::text(if is_error {
            "(the upstream reported an error without a message)"
        } else {
            "(empty result)"
        }));
    }
    let mut result = if is_error {
        CallToolResult::error(content)
    } else {
        CallToolResult::success(content)
    };
    result.structured_content = upstream
        .get("structuredContent")
        .filter(|v| v.is_object())
        .cloned();
    (result, is_error)
}

impl ServerHandler for PlaywrightServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                // Skills over MCP rides on the resources primitive: declaring
                // it is what makes `skill://` URIs discoverable at all.
                .enable_resources()
                .build(),
        )
        .with_server_info(Implementation::new(
            env!("CARGO_PKG_NAME"),
            env!("CARGO_PKG_VERSION"),
        ))
        .with_instructions(
            "Browser automation proxy: this sandboxed WebAssembly component forwards the \
             official Playwright MCP server's tools (browser_navigate, browser_snapshot, \
             browser_click, browser_type, browser_fill_form, browser_wait_for, \
             browser_take_screenshot, …) to `npx @playwright/mcp` running on the developer's \
             machine, keeping one browser session per warm instance and inlining the \
             accessibility snapshot after every action. Call `playwright_status` first — it \
             tells you whether the upstream is reachable and exactly how to fix the setup if \
             not — then snapshot before you act: element refs (`e4`) come only from \
             browser_snapshot/browser_find and go stale on every page change. \
             `playwright_reset_session` discards the browser context. Tools that run arbitrary \
             code or read host paths are hidden unless PLAYWRIGHT_ALLOW_UNSAFE=true.\n\n\
             This server publishes skills — playbooks describing when and how to use its \
             tools, the error catalogue and the upstream setup. Read `skill://index.json` for \
             the catalog, then `skill://playwright-mcp/SKILL.md`.",
        )
    }

    /// The tool surface: two local tools plus the upstream's list, gated and
    /// shaped. When the upstream cannot be reached only the local tools are
    /// listed — `playwright_status` says why — so a client can still connect.
    async fn list_tools(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListToolsResult, ErrorData> {
        let cfg = playwright::config();
        let mut tools = local_tools();
        let client = Client::new(cfg.clone());
        match client.tools().await {
            Ok(raw) => {
                for shaped in playwright::visible_tools(&raw, cfg.allow_unsafe) {
                    match serde_json::from_value::<Tool>(shaped) {
                        Ok(tool) => tools.push(tool),
                        Err(err) => {
                            tracing::warn!(error = %err, "skipping an upstream tool the SDK cannot model")
                        }
                    }
                }
            }
            Err(err) => tracing::warn!(
                error = %err.message(&cfg),
                "upstream tools/list unavailable; listing local tools only"
            ),
        }
        Ok(ListToolsResult::with_all_items(tools))
    }

    async fn call_tool(
        &self,
        request: CallToolRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<CallToolResponse, ErrorData> {
        let name = request.name.to_string();
        let arguments = request.arguments.unwrap_or_default();
        let result = match name.as_str() {
            STATUS_TOOL => self.playwright_status().await,
            RESET_TOOL => self.playwright_reset_session().await,
            _ => self.forward(&name, arguments).await?,
        };
        Ok(result.into())
    }

    /// Skills over MCP: every skill file, plus the catalog, as resources.
    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, ErrorData> {
        Ok(ListResourcesResult::with_all_items(skills::resources()))
    }

    /// Parameterized `skill://` URIs, so a client can construct a skill
    /// request without having enumerated every resource first.
    async fn list_resource_templates(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourceTemplatesResult, ErrorData> {
        Ok(ListResourceTemplatesResult::with_all_items(
            skills::resource_templates(),
        ))
    }

    #[tracing::instrument(name = "resources.read", skip(self, _context), fields(uri = %request.uri))]
    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResponse, ErrorData> {
        let (mime_type, text) = skills::read(&request.uri).ok_or_else(|| {
            ErrorData::resource_not_found(
                format!(
                    "no resource at {}; read {} for the skills this server serves",
                    request.uri,
                    skills::INDEX_URI
                ),
                None,
            )
        })?;
        Ok(ReadResourceResult::new(vec![
            ResourceContents::text(text, request.uri).with_mime_type(mime_type)
        ])
        .into())
    }
}
