package cosmonic:core-subscriber@0.1.0;

/// Core subscriber — Run a component once per message on a NATS subject.
world core-subscriber {
  import wasmcloud:nats/types@0.1.0;
  import wasmcloud:nats/jetstream@0.1.0;

  export wasmcloud:nats/core-handler@0.1.0;
}
