//! The `wasmcloud:postgres@0.2.0` client: configuration, the host-call
//! operations (`query`, `execute`, `execute_batch`), and the error model
//! tools render.
//!
//! ## How the database is reached
//!
//! The component never dials Postgres. Cosmonic Desktop registers the
//! `wasmcloud:postgres` plugin in *multiplex* mode: the workload manifest
//! declares named host interfaces (`db`, `db-prepared`) whose resolved config
//! carries the connection URL (from the `postgres-mcp-url` secret ref, env
//! key `url`), the daemon owns a connection pool per URL, and this component
//! reaches it through the labeled imports in `wit/world.wit`. That is why the
//! workload needs no `allowedHosts`, no loopback grant and no volumes.
//!
//! ## Threading model
//!
//! Every binding call is a WASI p3 future and must run in component-model
//! context, never from tool (tokio) code. The operations below therefore
//! wrap the whole exchange — the call, consuming the row stream, awaiting the
//! completion future — in one [`crate::bridge::host_call`] closure and hand
//! back plain data (`Vec<Vec<PgValue>>`), so tools only ever see values.

use std::sync::Mutex;

use serde_json::{json, Value};

use crate::bridge::{self, HostCallError};
use crate::pgvalue::{retry_param, Param};

/// Generated guest bindings for `wit/world.wit`: the shared `types`
/// interface plus the two labeled imports (`db` = `query`, `db-prepared` =
/// `prepared`). Generated by the same wit-bindgen 0.61 runtime `wasip3`
/// uses, so the two async executors are one and the same.
pub mod bindings {
    wit_bindgen::generate!({
        path: "wit",
        world: "postgres-mcp",
        generate_all,
    });
}

pub use bindings::wasmcloud::postgres::types::{DbError, Error as WitError, PgValue};

/// Name of the Desktop secret reference that carries the connection URL.
pub const SECRET_REF: &str = "postgres-mcp-url";
/// The config key the daemon's postgres provider reads from the named host
/// interface — the secret ref MUST be registered with this `env`.
pub const SECRET_ENV: &str = "url";
/// Placeholder URL for the podman `mcp-pg` container on a developer machine.
pub const EXAMPLE_URL: &str = "postgres://mcp:mcp@127.0.0.1:5432/mcp?sslmode=disable";

/// The one-paragraph remediation used everywhere a credential problem is
/// reported: names the ref, the env key, where the value comes from and the
/// exact registration call.
pub fn credential_hint() -> String {
    format!(
        "The database URL comes from the Desktop secret ref `{SECRET_REF}` (env key `{SECRET_ENV}`), \
         resolved by the daemon when the workload binds — the component never sees it. Fix the \
         value (postgres://USER:PASSWORD@HOST:5432/DBNAME?sslmode=disable|require; percent-encode \
         special characters in the password; use 127.0.0.1 for a database on this machine — the \
         daemon dials from the host process) with `cosmonic_set_secret name={SECRET_REF} \
         uri=keychain://cosmonic/{SECRET_REF} env={SECRET_ENV} value=<url>` (or Desktop → Secrets), \
         then re-apply deploy/workload.yaml so the new value is picked up, and call server_info. \
         Local example: {EXAMPLE_URL}."
    )
}

/// The `credentials` block of the discovery document (`GET /`): presence
/// only, never values. The workload cannot start without the ref, so a
/// running component implies `configured`.
pub fn credentials() -> Value {
    json!([{
        "ref": SECRET_REF,
        "env": SECRET_ENV,
        "kind": "postgres-url",
        "status": "configured",
        "description": "PostgreSQL connection URL (postgres://user:password@host:5432/dbname?sslmode=…); \
                        consumed by the wasmcloud:postgres host interfaces `db` and `db-prepared`, not by the \
                        component. Prefer a dedicated read-only role.",
        "obtainUrl": "https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING-URIS",
        "scopes": ["CONNECT", "USAGE on schemas", "SELECT on tables", "INSERT/UPDATE/DELETE/DDL only with POSTGRES_ALLOW_WRITES=true"],
        "validate": "server_info",
        "note": "Resolved by Cosmonic Desktop at workload bind time; a missing or mis-registered ref fails the bind (the server never starts) rather than a tool call."
    }])
}

// ── configuration ───────────────────────────────────────────────────────────

/// Named configuration read from the environment (see deploy/workload.yaml).
#[derive(Debug, Clone)]
pub struct Config {
    /// `POSTGRES_ALLOW_WRITES` == "true".
    pub allow_writes: bool,
    /// `POSTGRES_DEFAULT_ROW_LIMIT` (default 100).
    pub default_row_limit: usize,
    /// `POSTGRES_MAX_ROW_LIMIT` (default 1000).
    pub max_row_limit: usize,
    /// `POSTGRES_QUERY_TIMEOUT_MS` (default 30000).
    pub timeout_ms: u64,
    /// `POSTGRES_MAX_RESULT_BYTES` (default 1 MiB).
    pub max_result_bytes: usize,
    /// `POSTGRES_DEFAULT_SCHEMA` (default `public`).
    pub default_schema: String,
    /// `POSTGRES_HIDE_SYSTEM_SCHEMAS` != "false".
    pub hide_system_schemas: bool,
}

impl Config {
    pub fn from_env() -> Self {
        fn num<T: std::str::FromStr + Ord>(key: &str, default: T, lo: T, hi: T) -> T {
            std::env::var(key)
                .ok()
                .and_then(|v| v.trim().parse::<T>().ok())
                .unwrap_or(default)
                .clamp(lo, hi)
        }
        let max_row_limit = num("POSTGRES_MAX_ROW_LIMIT", 1000usize, 1, 100_000);
        Self {
            allow_writes: std::env::var("POSTGRES_ALLOW_WRITES")
                .is_ok_and(|v| v.trim().eq_ignore_ascii_case("true")),
            default_row_limit: num("POSTGRES_DEFAULT_ROW_LIMIT", 100usize, 1, max_row_limit),
            max_row_limit,
            timeout_ms: num("POSTGRES_QUERY_TIMEOUT_MS", 30_000u64, 1_000, 600_000),
            max_result_bytes: num(
                "POSTGRES_MAX_RESULT_BYTES",
                1024usize * 1024,
                4096,
                16 * 1024 * 1024,
            ),
            default_schema: std::env::var("POSTGRES_DEFAULT_SCHEMA")
                .ok()
                .map(|s| s.trim().to_owned())
                .filter(|s| !s.is_empty())
                .unwrap_or_else(|| "public".to_owned()),
            hide_system_schemas: !std::env::var("POSTGRES_HIDE_SYSTEM_SCHEMAS")
                .is_ok_and(|v| v.trim().eq_ignore_ascii_case("false")),
        }
    }

    /// Effective settings, for `server_info` and error messages.
    pub fn summary(&self) -> Value {
        json!({
            "writes_allowed": self.allow_writes,
            "default_row_limit": self.default_row_limit,
            "max_row_limit": self.max_row_limit,
            "query_timeout_ms": self.timeout_ms,
            "max_result_bytes": self.max_result_bytes,
            "default_schema": self.default_schema,
            "hide_system_schemas": self.hide_system_schemas,
            "max_cell_chars": crate::pgvalue::MAX_CELL_CHARS,
        })
    }
}

// ── errors ──────────────────────────────────────────────────────────────────

/// Everything that can go wrong between a tool and the database.
#[derive(Debug, Clone)]
pub enum PgError {
    /// The database rejected or failed the statement (`query-failed`).
    Db {
        code: String,
        severity: String,
        message: String,
        detail: Option<String>,
    },
    /// The host could not get/keep a connection (`connection-failed`); also
    /// where tokio-postgres client-side errors land (parameter encoding).
    ConnectionFailed(String),
    /// Host-side parameter validation (`invalid-params`).
    InvalidParams(String),
    /// Host-side statement rejection (`invalid-query`).
    InvalidQuery(String),
    /// A column could not be converted to a `pg-value` — the whole result
    /// is discarded (`value-conversion-failed`). `column` is the name when
    /// the query's column list was already known.
    ValueConversion {
        message: String,
        column: Option<String>,
    },
    /// Prepared-statement token unknown (after the automatic re-prepare).
    UnknownPrepared,
    /// The host refused this component access to the database.
    AccessDenied,
    /// The host's own time limit.
    HostTimeout,
    /// Backend-specific failure (`other`).
    Other(String),
    /// The component's deadline (`POSTGRES_QUERY_TIMEOUT_MS`) elapsed.
    Deadline(u64),
    /// The bridge went away (component teardown / client gone).
    BridgeClosed,
    /// Refused locally before reaching the host (inspector, params).
    Refused(String),
}

impl PgError {
    /// A rendering-time failure (a cell the host mis-decoded).
    pub fn cell(column: Option<&str>, reason: &str) -> Self {
        let col = column.map(|c| format!(" `{c}`")).unwrap_or_default();
        PgError::Refused(format!(
            "result column{col} cannot be rendered: {reason}. The host reads numeric/decimal/money \
             columns through a lossy path (binary bytes as text); cast the column in SQL — \
             `col::text` keeps the exact value, `col::float8` gives a JSON number — and use \
             describe_table to see column types first"
        ))
    }
}

impl From<WitError> for PgError {
    fn from(err: WitError) -> Self {
        match err {
            WitError::ConnectionFailed(m) => PgError::ConnectionFailed(m),
            WitError::InvalidParams(m) => PgError::InvalidParams(m),
            WitError::InvalidQuery(m) => PgError::InvalidQuery(m),
            WitError::QueryFailed(DbError {
                code,
                severity,
                message,
                detail,
                ..
            }) => PgError::Db {
                code,
                severity,
                message,
                detail,
            },
            WitError::ValueConversionFailed(m) => PgError::ValueConversion {
                message: m,
                column: None,
            },
            WitError::UnknownPreparedStatement => PgError::UnknownPrepared,
            WitError::AccessDenied => PgError::AccessDenied,
            WitError::Timeout => PgError::HostTimeout,
            WitError::Other(m) => PgError::Other(m),
        }
    }
}

impl From<HostCallError> for PgError {
    fn from(err: HostCallError) -> Self {
        match err {
            HostCallError::TimedOut(ms) => PgError::Deadline(ms),
            HostCallError::BridgeClosed => PgError::BridgeClosed,
        }
    }
}

impl PgError {
    /// SQLSTATE, when the database reported one.
    pub fn sqlstate(&self) -> Option<&str> {
        match self {
            PgError::Db { code, .. } => Some(code),
            _ => None,
        }
    }

    /// Short machine-readable kind for structured errors.
    pub fn kind(&self) -> &'static str {
        match self {
            PgError::Db { .. } => "query_failed",
            PgError::ConnectionFailed(_) => "connection_failed",
            PgError::InvalidParams(_) => "invalid_params",
            PgError::InvalidQuery(_) => "invalid_query",
            PgError::ValueConversion { .. } => "value_conversion_failed",
            PgError::UnknownPrepared => "unknown_prepared_statement",
            PgError::AccessDenied => "access_denied",
            PgError::HostTimeout => "host_timeout",
            PgError::Other(_) => "other",
            PgError::Deadline(_) => "timeout",
            PgError::BridgeClosed => "bridge_closed",
            PgError::Refused(_) => "refused",
        }
    }

    /// The client-facing message: what happened, then what to do about it.
    pub fn render(&self) -> String {
        match self {
            PgError::Db {
                code,
                severity,
                message,
                detail,
            } => {
                let mut out = format!("{severity} {code} ({}): {message}", sqlstate_name(code));
                if let Some(d) = detail.as_deref().filter(|d| !d.is_empty()) {
                    out.push_str(&format!(" — {}", d.trim_end_matches('.')));
                }
                if let Some(hint) = sqlstate_hint(code, message) {
                    out.push_str(&format!(". Hint: {hint}"));
                }
                out
            }
            PgError::ConnectionFailed(m) => format!(
                "connection failed: {m}. Hint: {}",
                connection_hint(m)
            ),
            PgError::InvalidParams(m) => format!(
                "invalid parameters: {m}. Hint: params are positional ($1..$n, in order); pass typed \
                 values as {{\"type\": \"int4\"|\"uuid\"|\"timestamptz\"|…, \"value\": …}} where the \
                 column type is not text/int8/float8/bool — describe_table shows column types"
            ),
            PgError::InvalidQuery(m) => format!("the host rejected the statement: {m}"),
            PgError::ValueConversion { message, column } => {
                let name = column
                    .as_deref()
                    .map(|n| format!(" (`{n}`)"))
                    .unwrap_or_default();
                let expr = column.clone().unwrap_or_else(|| "col".to_owned());
                format!(
                    "the host cannot convert a result column{name}: {message}. The whole result \
                     is discarded when any column has a type the host's value conversion does not \
                     handle: numeric/decimal/money (most values), enum, char(n), oid/regclass/\
                     regproc, interval, timetz, range/multirange, circle/line, void (pg_sleep), \
                     record, tsquery/tsvector. Hint: cast it in SQL (`{expr}::text` — exact for \
                     numeric —, `{expr}::float8`, intervals `EXTRACT(EPOCH FROM {expr})`, oids \
                     `{expr}::int`), avoid SELECT * on unfamiliar tables, and use describe_table to \
                     see column types first"
                )
            }
            PgError::UnknownPrepared => "the prepared statement was evicted by the host and could \
                 not be re-prepared; retry the call once"
                .to_owned(),
            PgError::AccessDenied => "access denied: the host refused this component's access to \
                 the database. Hint: check the workload's wasmcloud:postgres hostInterfaces (db, \
                 db-prepared) and Desktop policy, then re-apply"
                .to_owned(),
            PgError::HostTimeout => "the host's time limit expired before the call completed. \
                 Hint: narrow the query (WHERE/LIMIT), explain_query first, or raise \
                 statement_timeout via the URL options"
                .to_owned(),
            PgError::Other(m) => {
                if m.contains("no database configured for this component") {
                    format!(
                        "{m}. The component reached the daemon through an UNNAMED postgres import \
                         (legacy path); this build must import `db` / `db-prepared` labels and the \
                         workload must declare hostInterfaces with those names — rebuild \
                         (cosmonic_inspect must list `db` and `db-prepared`), re-promote, re-apply"
                    )
                } else {
                    format!("database backend error: {m}")
                }
            }
            PgError::Deadline(ms) => format!(
                "timeout: no result within {ms} ms (POSTGRES_QUERY_TIMEOUT_MS). The row stream was \
                 dropped so the host stopped fetching, but the statement may still be running on \
                 the server. Hint: add WHERE/LIMIT, run explain_query first, set \
                 `options=-c statement_timeout=30000` (URL-encoded) in the connection URL so Postgres \
                 cancels runaway statements (they then fail with 57014), or raise \
                 POSTGRES_QUERY_TIMEOUT_MS"
            ),
            PgError::BridgeClosed => "the request ended before the database call completed (client \
                 disconnected or component shutting down); retry"
                .to_owned(),
            PgError::Refused(m) => m.clone(),
        }
    }

    /// Structured form for `structuredContent` alongside the message.
    pub fn to_json(&self) -> Value {
        json!({
            "error": self.kind(),
            "sqlstate": self.sqlstate(),
            "message": self.render(),
        })
    }
}

/// Human name of the common SQLSTATEs (the rest fall back to the class).
fn sqlstate_name(code: &str) -> &'static str {
    match code {
        "42P01" => "undefined_table",
        "42703" => "undefined_column",
        "42601" => "syntax_error",
        "42501" => "insufficient_privilege",
        "42883" => "undefined_function",
        "42804" => "datatype_mismatch",
        "42P18" => "indeterminate_datatype",
        "42P02" => "undefined_parameter",
        "42702" => "ambiguous_column",
        "42P07" => "duplicate_table",
        "42710" => "duplicate_object",
        "42846" => "cannot_coerce",
        "3F000" => "invalid_schema_name",
        "3D000" => "invalid_catalog_name",
        "22P02" => "invalid_text_representation",
        "22P03" => "invalid_binary_representation",
        "22003" => "numeric_value_out_of_range",
        "22007" => "invalid_datetime_format",
        "22008" => "datetime_field_overflow",
        "22012" => "division_by_zero",
        "22001" => "string_data_right_truncation",
        "23505" => "unique_violation",
        "23503" => "foreign_key_violation",
        "23502" => "not_null_violation",
        "23514" => "check_violation",
        "25006" => "read_only_sql_transaction",
        "25P02" => "in_failed_sql_transaction",
        "28P01" => "invalid_password",
        "28000" => "invalid_authorization_specification",
        "53300" => "too_many_connections",
        "57014" => "query_canceled",
        "55P03" => "lock_not_available",
        "40001" => "serialization_failure",
        "40P01" => "deadlock_detected",
        "08P01" => "protocol_violation",
        "0A000" => "feature_not_supported",
        "2BP01" => "dependent_objects_still_exist",
        _ => match code.get(..2) {
            Some("42") => "syntax_error_or_access_rule_violation",
            Some("22") => "data_exception",
            Some("23") => "integrity_constraint_violation",
            Some("25") => "invalid_transaction_state",
            Some("28") => "invalid_authorization",
            Some("53") => "insufficient_resources",
            Some("57") => "operator_intervention",
            Some("08") => "connection_exception",
            Some("XX") => "internal_error",
            _ => "error",
        },
    }
}

/// What to do about a given SQLSTATE.
fn sqlstate_hint(code: &str, message: &str) -> Option<String> {
    let hint = match code {
        "42P01" => {
            "the table does not exist under that name/schema — list_tables or \
                    search_objects to find it, qualify it as schema.table, and quote mixed-case \
                    names (\"MyTable\")"
        }
        "42703" => {
            "the column does not exist — describe_table shows the real names; quote \
                    mixed-case names"
        }
        "42601" if message.contains("multiple commands") => {
            "only one statement per call: send \
                    them one at a time, or use execute_batch (writes on) for a script"
        }
        "42601" => {
            "check the syntax at the reported position; placeholders are $1..$n (never ? \
                    or :name); identifiers with capitals need double quotes"
        }
        "42501" => {
            "the URL's role lacks privileges — GRANT USAGE ON SCHEMA … / GRANT SELECT ON … \
                    TO that role, or point the postgres-mcp-url secret at a different role"
        }
        "25006" => {
            "the connection's role is read-only at the database level \
                    (default_transaction_read_only=on or a standby) — by design; use a different \
                    role/URL for writes"
        }
        "22P03" | "22021" => {
            "a parameter's binary encoding does not match the type Postgres inferred for it, \
             and no automatic re-encoding fit. Run describe_table, then pass a typed param \
             ({\"type\": \"int4\"|\"uuid\"|\"timestamptz\"|\"numeric\"|\"date\"|\"bytea\"|…, \
             \"value\": …}) or cast from text in SQL ($N::text::uuid); note `$N::int` alone does \
             not help"
        }
        "08P01" if message.contains("insufficient data") => {
            "a parameter's binary encoding is shorter than the type Postgres inferred for it \
             expects (e.g. a string where a number/uuid/timestamp is needed) and no automatic \
             re-encoding fit — pass a typed param ({\"type\": …, \"value\": …}) or cast from \
             text ($N::text::<type>)"
        }
        "22023" if message.contains("jsonb") => {
            "a jsonb parameter must be a JSON object/array or {\"type\": \"jsonb\", \"value\": …}, \
             not a string"
        }
        "42P18" => {
            "Postgres cannot infer the parameter's type there (SELECT $1, LIMIT $1, \
                    COALESCE) — cast the placeholder: $1::text, $1::bigint"
        }
        "42P02" => "the statement references a $N placeholder with no matching entry in params",
        "08P01" => "the number of params must equal the highest $N used, in order",
        "22P02" | "42804" | "42846" | "42883" => {
            "a value or cast does not fit the target type — \
                    fix the value or the cast; describe_table shows column types"
        }
        "57014" => {
            "the server-side statement_timeout fired — narrow the query or raise the \
                    timeout deliberately"
        }
        "53300" => {
            "the database's connection limit is reached — lower concurrency, add \
                    `&pool_size=N` to the URL, or raise max_connections"
        }
        "23505" | "23503" | "23502" | "23514" => {
            "a constraint rejected the write — describe_table \
                    lists constraints; use ON CONFLICT or fix the referenced rows"
        }
        "3F000" => "the schema does not exist — list_schemas",
        "0A000" => "the server does not support this operation",
        "40001" | "40P01" => "transient serialization/deadlock failure — retry the statement",
        "55P03" => "another session holds a conflicting lock — retry later",
        _ => return None,
    };
    Some(hint.to_owned())
}

/// What to do about a `connection-failed` message.
fn connection_hint(message: &str) -> String {
    let m = message.to_ascii_lowercase();
    if m.contains("parameters but got") {
        return "the number of params must equal the highest $N placeholder used, in order"
            .to_owned();
    }
    if m.contains("error serializing parameter") {
        return "a parameter could not be encoded for its inferred type — pass a typed param \
                ({\"type\": …, \"value\": …}) or cast from text in SQL ($N::text::<type>)"
            .to_owned();
    }
    if !m.contains("failed to get connection") && !m.contains("connect") && !m.contains("tls") {
        return format!(
            "this is a client-side error from the daemon's postgres driver, not a connectivity \
             problem — check the statement and its parameters (describe_table for column types). \
             If it persists, call server_info; the connection itself is configured by the secret \
             ref `{SECRET_REF}`"
        );
    }
    if m.contains("password authentication failed") || m.contains("28p01") || m.contains("28000") {
        format!("the URL's credentials are wrong. {}", credential_hint())
    } else if m.contains("does not exist") && m.contains("database") || m.contains("3d000") {
        format!(
            "the URL names a database that does not exist. {}",
            credential_hint()
        )
    } else if m.contains("connection refused")
        || m.contains("error connecting to server")
        || m.contains("timed out")
        || m.contains("could not connect")
        || m.contains("no route")
        || m.contains("name resolution")
        || m.contains("dns")
    {
        format!(
            "the database is not reachable from the Cosmonic Desktop DAEMON (it dials the URL from \
             the host process; the component does not). Check host:port from this machine \
             (`podman start mcp-pg` for the local container), firewalls, and sslmode. {}",
            credential_hint()
        )
    } else if m.contains("certificate") || m.contains("unknownissuer") || m.contains("tls") {
        "TLS failed: with sslmode=require|verify-* the daemon trusts webpki (public CA) roots \
         only, so self-signed/private-CA servers fail — use a publicly trusted certificate or \
         sslmode=disable on a trusted network"
            .to_owned()
    } else if m.contains("pool") || m.contains("timeout") {
        "the daemon's connection pool is exhausted or the server is slow — lower concurrency or \
         add `&pool_size=N` to the URL"
            .to_owned()
    } else {
        credential_hint()
    }
}

// ── operations ──────────────────────────────────────────────────────────────

/// Rows straight from the host (converted to JSON by the tools).
#[derive(Debug)]
pub struct RawResult {
    pub columns: Vec<String>,
    pub rows: Vec<Vec<PgValue>>,
    /// More rows existed than `max_rows`; the stream was dropped early.
    pub truncated: bool,
}

/// Bind-format retries per call (each fixes one parameter's encoding).
const MAX_BIND_RETRIES: usize = 16;

/// "incorrect binary data format in bind parameter N" → N.
fn bind_param_index(message: &str) -> Option<usize> {
    let rest = message.split("bind parameter ").nth(1)?;
    rest.trim()
        .trim_end_matches(|c: char| !c.is_ascii_digit())
        .parse()
        .ok()
}

/// Whether the database rejected a parameter's *encoding* (as opposed to its
/// value): the cases the retry chain in [`crate::pgvalue`] can fix.
fn is_bind_format_error(err: &PgError) -> bool {
    let PgError::Db { code, message, .. } = err else {
        return false;
    };
    let m = message.to_ascii_lowercase();
    match code.as_str() {
        // invalid_binary_representation: wrong length, bad numeric sign, …
        "22P03" => true,
        // protocol_violation: too few bytes for the slot's type.
        "08P01" => m.contains("insufficient data") || m.contains("invalid message format"),
        // character_not_in_repertoire: a NUL byte from an integer encoding
        // landed in a text slot.
        "22021" => m.contains("0x00"),
        // invalid_parameter_value: jsonb version byte from text bytes.
        "22023" => m.contains("jsonb version"),
        _ => false,
    }
}

/// Re-encodes the parameter a bind-format error points at. When the message
/// names none (`08P01`, `22021`, `22023`) the culprit is only certain if
/// exactly one auto-typed parameter still has an untried encoding; with
/// several, guessing would thrash (and could land on a silent misread), so
/// the call fails with the attempts listed and typed params are the fix.
/// `false` when nothing is left to try.
fn retype(params: &mut [Param], err: &PgError) -> bool {
    if !is_bind_format_error(err) {
        return false;
    }
    let PgError::Db { message, .. } = err else {
        return false;
    };
    if let Some(index) = bind_param_index(message) {
        let Some(slot) = index.checked_sub(1).and_then(|i| params.get_mut(i)) else {
            return false;
        };
        return match retry_param(slot) {
            Some(next) => {
                *slot = next;
                true
            }
            None => false,
        };
    }
    let mut candidates = params
        .iter_mut()
        .filter(|p| retry_param(p).is_some())
        .collect::<Vec<_>>();
    match candidates.as_mut_slice() {
        [only] => {
            if let Some(next) = retry_param(only) {
                **only = next;
                return true;
            }
            false
        }
        _ => false,
    }
}

/// Whether an unindexed bind error could not be attributed to one parameter.
fn ambiguous_bind(params: &[Param], err: &PgError) -> bool {
    let PgError::Db { message, .. } = err else {
        return false;
    };
    bind_param_index(message).is_none()
        && params.iter().filter(|p| retry_param(p).is_some()).count() > 1
}

/// After the retry chain is exhausted: which parameter encodings were tried,
/// so the caller can pick a typed parameter or a cast.
fn attempts_summary(params: &[Param]) -> String {
    let tried: Vec<String> = params
        .iter()
        .enumerate()
        .filter(|(_, p)| p.typing != crate::pgvalue::Typing::Fixed)
        .map(|(i, p)| format!("${} {}", i + 1, crate::pgvalue::describe_attempts(p)))
        .collect();
    if tried.is_empty() {
        String::new()
    } else {
        format!(" Parameter encodings tried: {}", tried.join("; "))
    }
}

/// Appends the encodings tried to a bind-format error's message.
fn with_attempts(err: PgError, params: &[Param]) -> PgError {
    let ambiguous = ambiguous_bind(params, &err);
    match err {
        PgError::Db {
            code,
            severity,
            message,
            detail,
        } => PgError::Db {
            code,
            severity,
            message: format!(
                "{}.{}{}",
                message.trim_end_matches('.'),
                attempts_summary(params),
                if ambiguous {
                    " (the error names no parameter and more than one auto-typed parameter \
                     could be re-encoded, so no guess was made — pass typed params)"
                } else {
                    ""
                }
            ),
            detail,
        },
        other => other,
    }
}

fn values(params: &[Param]) -> Vec<PgValue> {
    params.iter().map(|p| p.value.clone()).collect()
}

/// Runs one parameterized statement, returning at most `max_rows` rows
/// (`truncated` says whether more existed). Bare integer/float parameters
/// that Postgres rejects with `22P03` are re-sent with narrower types
/// automatically (int8 → int4 → int2 → numeric; float8 → float4 → numeric).
pub async fn query(
    config: &Config,
    sql: String,
    params: Vec<Param>,
    max_rows: usize,
) -> Result<RawResult, PgError> {
    let outcome = bridge::host_call(config.timeout_ms, move || async move {
        let mut params = params;
        let mut attempts = 0usize;
        loop {
            match query_once(&sql, values(&params), max_rows).await {
                Err(err) if attempts < MAX_BIND_RETRIES && retype(&mut params, &err) => {
                    attempts += 1;
                }
                Err(err) if is_bind_format_error(&err) => {
                    return Err(with_attempts(err, &params));
                }
                other => return other,
            }
        }
    })
    .await?;
    outcome
}

/// One `db.query` exchange in component-model context.
async fn query_once(
    sql: &str,
    params: Vec<PgValue>,
    max_rows: usize,
) -> Result<RawResult, PgError> {
    let (columns, mut stream, done) = bindings::db::query(sql.to_owned(), params).await?;
    let mut rows = Vec::new();
    let mut truncated = false;
    while let Some(row) = stream.next().await {
        if rows.len() >= max_rows {
            truncated = true;
            break;
        }
        rows.push(row);
    }
    // Dropping the reader cancels the host's fetch task; the completion
    // future then resolves (Ok once the task notices, or with the error the
    // task hit first — which is the real outcome when nothing was cut).
    drop(stream);
    match done.await {
        Ok(()) => Ok(RawResult {
            columns,
            rows,
            truncated,
        }),
        Err(err) if truncated => {
            tracing::debug!(error = ?err, "completion error after an early stream drop");
            Ok(RawResult {
                columns,
                rows,
                truncated,
            })
        }
        Err(err) => Err(name_column(err.into(), &columns)),
    }
}

/// "column N: …" from the host → the column's name, when the header is known.
fn name_column(err: PgError, columns: &[String]) -> PgError {
    match err {
        PgError::ValueConversion {
            message,
            column: None,
        } => {
            let column = message
                .strip_prefix("column ")
                .and_then(|rest| rest.split(':').next())
                .and_then(|n| n.trim().parse::<usize>().ok())
                .and_then(|i| columns.get(i).cloned());
            PgError::ValueConversion { message, column }
        }
        other => other,
    }
}

/// Per-instance prepared-statement cache (SQL text → host token), bounded
/// and least-recently-used. Statics survive across requests on a warm
/// instance, which is exactly the lifetime of the host's token table for
/// this component.
fn prepared_cache() -> &'static Mutex<Vec<(String, String)>> {
    use std::sync::OnceLock;
    static CACHE: OnceLock<Mutex<Vec<(String, String)>>> = OnceLock::new();
    CACHE.get_or_init(|| Mutex::new(Vec::new()))
}

const PREPARED_CACHE_SIZE: usize = 64;

fn cached_token(sql: &str) -> Option<String> {
    let mut cache = prepared_cache().lock().ok()?;
    let pos = cache.iter().position(|(s, _)| s == sql)?;
    let entry = cache.remove(pos);
    let token = entry.1.clone();
    cache.push(entry);
    Some(token)
}

fn remember_token(sql: &str, token: &str) {
    if let Ok(mut cache) = prepared_cache().lock() {
        cache.retain(|(s, _)| s != sql);
        if cache.len() >= PREPARED_CACHE_SIZE {
            cache.remove(0);
        }
        cache.push((sql.to_owned(), token.to_owned()));
    }
}

fn forget_token(sql: &str) {
    if let Ok(mut cache) = prepared_cache().lock() {
        cache.retain(|(s, _)| s != sql);
    }
}

/// Runs one writing/DDL statement through `db-prepared` (prepare once per
/// instance, then exec) and returns the number of rows affected. Handles the
/// host evicting the token (re-prepares once) and the same `22P03` retries as
/// [`query`].
pub async fn execute(config: &Config, sql: String, params: Vec<Param>) -> Result<u64, PgError> {
    let outcome = bridge::host_call(config.timeout_ms, move || async move {
        let mut params = params;
        let mut attempts = 0usize;
        let mut reprepared = false;
        let mut token = match cached_token(&sql) {
            Some(t) => t,
            None => prepare(&sql).await?,
        };
        loop {
            match bindings::db_prepared::exec(token.clone(), values(&params)).await {
                Ok(n) => return Ok(n),
                Err(WitError::UnknownPreparedStatement) if !reprepared => {
                    reprepared = true;
                    forget_token(&sql);
                    token = prepare(&sql).await?;
                }
                Err(err) => {
                    let err = PgError::from(err);
                    if attempts < MAX_BIND_RETRIES && retype(&mut params, &err) {
                        attempts += 1;
                        continue;
                    }
                    if is_bind_format_error(&err) {
                        return Err(with_attempts(err, &params));
                    }
                    return Err(err);
                }
            }
        }
    })
    .await?;
    outcome
}

async fn prepare(sql: &str) -> Result<String, PgError> {
    let token = bindings::db_prepared::prepare(sql.to_owned()).await?;
    remember_token(sql, &token);
    Ok(token)
}

/// Runs a multi-statement script with no parameters on one connection
/// (single implicit transaction unless the script has its own BEGIN/COMMIT).
pub async fn execute_batch(config: &Config, sql: String) -> Result<(), PgError> {
    let outcome = bridge::host_call(config.timeout_ms, move || async move {
        bindings::db::query_batch(sql).await.map_err(PgError::from)
    })
    .await?;
    outcome
}
