package cosmonic:kv-watcher@0.1.0;

/// KV watcher — React to every change in a JetStream KV bucket.
world kv-watcher {
  import wasmcloud:nats/types@0.1.0;
  import wasmcloud:nats/kv@0.1.0;
  import wasmcloud:nats/jetstream@0.1.0;

  export wasmcloud:nats/kv-handler@0.1.0;
}
